cursor                #ffb59f
cursor_text_color     #561f0e

foreground            #f1dfda
background            #1a110f
selection_foreground  #561f0e
selection_background  #ffb59f
url_color             #ffb59f

# black
color0   #1a110f
color8   #423734

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #d8c58d
color10  #524619

# yellow
color3   #e7bdb2
color11  #5d4037

# blue
color4   #ffb59f
color12  #723522

# magenta
color5   #d8c58d
color13  #f5e1a7

# cyan
color6   #e7bdb2
color14  #ffdbd1

# white
color7   #d8c2bc
color15  #f1dfda
