## Symphony by vyrx
## Theme: Vague
## https://github.com/vyrx-dev

background #121314
foreground #cdcdcd
selection_background #252530
selection_foreground #cdcdcd
cursor #aeaed1
cursor_text_color #121314

# Tabs
active_tab_background #aeaed1
active_tab_foreground #121314
inactive_tab_background #1a1b1c
inactive_tab_foreground #666677

# Windows
active_border_color #aeaed1
inactive_border_color #252530

# normal
color0 #252530
color1 #d8647e
color2 #7fa563
color3 #f3be7c
color4 #6e94b2
color5 #bb9dbd
color6 #aeaed1
color7 #cdcdcd

# bright
color8 #606079
color9 #e08398
color10 #99b782
color11 #f5cb96
color12 #8ba9c1
color13 #c9b1ca
color14 #bebeda
color15 #d7d7d7
