add_newline = false
command_timeout = 60
format = """$os$hostname $directory $git_branch$git_status$line_break$character"""

# right_format = """# $time# """

palette = "colors"

[palettes.colors]
mustard = '#af8700'
color1 = '#89b482'        # directory path (cyan accent)
color2 = '#111313'          # unused
color3 = '#ddc7a1'          # unused
color4 = '#111313'          # unused
color5 = '#111313'          # unused
color6 = '#32302f'        # vicmd symbol (muted gray)
color7 = '#111313'          # unused
color8 = '#89b482'        # os symbol, success character (primary)
color9 = '#d3869b'     # git branch (secondary accent)
error = '#ea6962'          # error character

[hostname]
ssh_only = true
style = "fg:color8"
format = "[ @$hostname]($style)"

[directory]
style = "fg:color1 bold"
read_only = " 󰌾"
read_only_style = "fg:#ea6962"
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:color8 bold)'
error_symbol = '[❯](fg:error bold)'
vicmd_symbol = '[❮](fg:color6 bold)'

[git_branch]
style = "fg:color9 bold"
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#ea6962)]($style)'

[os]
format = "[$symbol]($style)"
style = "fg:color8 bold"
disabled = false

[os.symbols]
Linux = "󰊠"
Arch = "󰣇"
Ubuntu = "󰕈"

# [time]
# disabled = false
# format = '[[ $time ](fg:#ea6962 )]($style)'
# time_format = "%R"

[line_break]
disabled = true

