#!/bin/bash

# Directory containing wallpapers
WALLPAPER_DIR="$HOME/Wallpapers/"
STATE_FILE="$HOME/.current_wallpaper_index"

mapfile -t WALLPAPERS < <(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) | sort)

# Get number of wallpapers
NUM_WALLPAPERS=${#WALLPAPERS[@]}
if [ "$NUM_WALLPAPERS" -eq 0 ]; then
  echo "No wallpapers found in $WALLPAPER_DIR"
  exit 1
fi

if [ -f "$STATE_FILE" ]; then
  INDEX=$(<"$STATE_FILE")
  INDEX=$((RANDOM % NUM_WALLPAPERS))
  # INDEX=$(((INDEX + 1) % NUM_WALLPAPERS)) #cycles through wallpapers in sequence
else
  INDEX=0
fi

echo "$INDEX" >"$STATE_FILE"

CURRENT_WALLPAPER="${WALLPAPERS[$INDEX]}"

swww img "$CURRENT_WALLPAPER" --transition-type=any --transition-fps 60 --transition-duration=1
# SWWW_PARAMS="--transition-fps 60 --transition-type=any --transition-duration=1"
matugen image "$CURRENT_WALLPAPER"
# wal -i "$CURRENT_WALLPAPER"
pywalfox update
hyprctl reload 2>/dev/null
restart-app waybar 2>/dev/null
restart-app swayosd-server 2>/dev/null
makoctl reload 2>/dev/null
killall -SIGUSR1 kitty
pkill -SIGUSR1 alacritty 2>/dev/null
pkill -SIGUSR2 btop 2>/dev/null
ghostty +reload-config 2>/dev/null
killall -SIGUSR2 ghosttyify text

pgrep -x nautilus >/dev/null && (
  pkill -x nautilus
  nautilus &>/dev/null &
  disown
)
restart-app swaync
killall wlogout
notify-send -i "$CURRENT_WALLPAPER" "Theme changed" "Wallpaper has been updated."
