#!/bin/bash

export LIBVA_DRIVER_NAME=radeonsi

browser=$(xdg-settings get default-web-browser)

case $browser in
brave-browser* | google-chrome* | microsoft-edge* | opera* | vivaldi* | helium-browser*) ;;
*) browser="brave-browser.desktop" ;;
esac

browser_exec=$(sed -n 's/^Exec=\([^ ]*\).*/\1/p' /usr/share/applications/$browser 2>/dev/null | head -1)

exec setsid uwsm-app -- $browser_exec --app="$1" "${@:2}"
