#!/bin/bash

if pgrep -x hypridle >/dev/null; then
  pkill -x hypridle
  notify-send "Screen Lock" "Off - Display will stay on"
else
  uwsm-app -- hypridle >/dev/null 2>&1 &
  notify-send "Screen Lock" "On - Display will sleep when inactive"
fi

pkill -RTMIN+9 waybar
