#!/bin/bash

if grep -q 'background_opacity 0.75' ~/.config/kitty/kitty.conf; then
  sed -i 's/background_opacity 0.75/background_opacity 1/g' ~/.config/kitty/kitty.conf
  echo "Done! set to 1.0"
elif grep -q 'background_opacity 1' ~/.config/kitty/kitty.conf; then
  sed -i 's/background_opacity 1/background_opacity 0.75/g' ~/.config/kitty/kitty.conf
  echo "Done! set to 0.75"
else
  echo "There is no background_opacity is present in the kitty theme...😥"
fi

pkill -SIGUSR1 -x kitty 2>/dev/null
