;; Symphony
;; Author: vyrx
;; Theme: Omarchy aetheria (omarchy)

[base]
text               = 14B9B5
subtext            = c53253
nav-active-text    = BE3F50
main               = 0e091d
sidebar            = 0e091d
player             = 0e091d
card               = 0e091d
shadow             = 000000
main-secondary     = 0e091d
button             = 221d31
button-secondary   = FF7F41
button-active      = BE3F50
button-disabled    = 040013
nav-active         = 221d31
play-button        = BE3F50
tab-active         = 0e091d
notification       = 0e091d
notification-error = 0e091d
playback-bar       = BE3F50
misc               = c53253
