# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗    ██████╗ ██╗   ██╗██╗     ███████╗███████╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║    ██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║    ██████╔╝██║   ██║██║     █████╗  ███████╗
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║    ██╔══██╗██║   ██║██║     ██╔══╝  ╚════██║
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝    ██║  ██║╚██████╔╝███████╗███████╗███████║
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝

# windowrulev2 = float, size 800 600, center, class:^(floatterm)$
# windowrule = float, title:^(webapp-install)$

windowrulev2 = float, class:floatterm
windowrulev2 = center, class:floatterm
windowrulev2 = size 800 500, class:floatterm

windowrulev2 = float, class:impala
windowrulev2 = center, class:impala
windowrulev2 = size 900 600, class:impala

windowrulev2 = float, class:wifibt
windowrulev2 = center, class:wifibt
windowrulev2 = size 600 500, class:wifibt

windowrulev2 = float, title:Bluetooth
windowrulev2 = center, title:Bluetooth
windowrulev2 = size 900 600, class:blueberry.py

windowrulev2 = float, title:webapp-install
windowrulev2 = center, title:webapp-install
windowrulev2 = size 900 600, title:webapp-install

windowrulev2 = float, title:share
windowrulev2 = center, title:share
windowrulev2 = size 900 600, title:share
windowrulev2 = animation slide, title:share  # Optional: nice animation

windowrulev2 = float, class:april
windowrulev2 = center, class:april
windowrulev2 = size 800 500, class:april

windowrulev2 = float, class:org.pulseaudio.pavucontrol
windowrulev2 = center, class:org.pulseaudio.pavucontrol
windowrulev2 = size 800 600, class:org.pulseaudio.pavucontrol

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, class:.*

windowrule = float, center, class:localsend
windowrule = center, class:localsend
windowrulev2 = size 600 600, class:localsend

windowrule = fullscreen, class:Screensaver

windowrule = noscreenshare, class:^(Bitwarden)$

# Assign Discord/Vesktop to workspace 10
windowrulev2 = workspace 10, class:^(vesktop|discord)$

layerrule = noanim, selection

####################
####  BROWSER  #####
####################

# Browser types
windowrule = tag +chromium-based-browser, class:((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium)
windowrule = tag +firefox-based-browser, class:([fF]irefox|zen|librewolf)

# Force chromium-based browsers into a tile to deal with --app bug
windowrule = tile, tag:chromium-based-browser

# Only a subtle opacity change, but not for video sites
windowrule = opacity 1 0.97, tag:chromium-based-browser
windowrule = opacity 1 0.97, tag:firefox-based-browser


# Some video sites should never have opacity applied to them
windowrule = opacity 1.0 1.0, initialTitle:((?i)(?:[a-z0-9-]+\.)*youtube\.com_/|app\.zoom\.us_/wc/home)

####################
####  Webcam   #####
####################
# Webcam overlay for screen recording
windowrule = float, title:WebcamOverlay
windowrule = pin, title:WebcamOverlay
windowrule = noinitialfocus, title:WebcamOverlay
windowrule = nodim, title:WebcamOverlay
windowrule = move 100%-w-40 100%-w-40, title:WebcamOverlay # There's a typo in the hyprland rule so 100%-w on the height param is actually correct here


####################
####    PIP    #####
####################
# Picture-in-picture overlays
windowrule = tag +pip, title:(Picture.?in.?[Pp]icture)
windowrule = float, tag:pip
windowrule = pin, tag:pip
windowrule = size 600 338, tag:pip
windowrule = keepaspectratio, tag:pip
windowrule = noborder, tag:pip
windowrule = opacity 1 1, tag:pip
windowrule = move 100%-w-40 4%, tag:pip

