# ~/.config/mpd/mpd.conf

music_directory     "~/Music/mpd"
playlist_directory  "~/Music/Playlists"

auto_update         "yes" #automatically updates db
bind_to_address    "127.0.0.1" #localhost
# bind_to_address will use the MPD_HOST environment variable if set
# Otherwise, uncomment and set your user ID manually:
# bind_to_address    "/run/user/1000/mpd/socket"
restore_paused     "yes" #startup behaviour
max_output_buffer_size "16384"

# Audio output for your system (choose one)
audio_output {
    type "pulse"
    name "pulse audio"
}

# # audio visualizer setup
# audio_output {
#     type "fifo"
#     name "Visualizer feed"
#     path "/tmp/mpd.fifo"
#     format "44100:16:2"
# }
