#!/bin/bash

scrDir="$HOME/.config/hypr/scripts"

options="Shutdown\nReboot\nSuspend\nLogout"

choice=$(echo -e "$options" | rofi -dmenu -p "" -config "$HOME/.config/rofi/custom-rofi/config-powermenu.rasi")

case "$choice" in
"Shutdown")
	"$scrDir/graceful-shutdown"
	;;
"Reboot")
	"$scrDir/graceful-reboot"
	;;
"Suspend")
	systemctl suspend
	;;
"Logout")
	if pgrep -x uwsm >/dev/null; then
		uwsm stop
	else
		hyprctl dispatch exit
	fi
	;;
esac
