#!/bin/bash
# wallpaper picker only, no theme changes

if command -v swww >/dev/null 2>&1; then
    wallbin=swww
elif command -v awww >/dev/null 2>&1; then
    wallbin=awww
else
    noitfy-send "No wallpaper daemon found" "Please install awww or swww and try again"
    exit 1 
fi

wallpaper_dir="$HOME/Wallpapers"
swww_params="--transition-fps 120 --transition-type center --transition-pos bottom --transition-duration 1 --transition-bezier 0.25,0.1,0.25,1.0"

mapfile -d '' wallpapers < <(find "$wallpaper_dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) -print0)

if [[ ${#wallpapers[@]} -eq 0 ]]; then
	(action=$(notify-send -A "open=Get Wallpapers" --wait "No Wallpapers Found" "Add images to ~/Wallpapers to use dynamic theming") && [[ "$action" == "open" ]] && xdg-open "https://github.com/vyrx-dev/Wallpapers") &
	exit 1
fi

menu() {
	for wp in "${wallpapers[@]}"; do
		printf "%s\x00icon\x1f%s\n" "$(basename "$wp")" "$wp"
	done | sort
}

"$wallbin" query &>/dev/null || "$wallbin"-daemon --format xrgb

choice=$(menu | rofi -i -dmenu -p "" -config ~/.config/rofi/custom-rofi/config-wallpaper.rasi)
[[ -z "$choice" ]] && exit 0

for wp in "${wallpapers[@]}"; do
	[[ "$(basename "$wp")" == "$choice" ]] || continue

	"$wallbin" img "$wp" $swww_params

	# update wallpaper symlink for hyprlock
	mkdir -p "$HOME/.config/symphony/current"
	ln -sf "$wp" "$HOME/.config/symphony/current/wallpaper"

	notify-send -i "$wp" "Wallpaper" "${wp##*/}"
	break
done
