set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

####  PREFIX KEY ####
unbind C-b
set -g prefix C-s  #Suggestion: Remap CAPSLOCK to CTRL

####  RELOAD  tmux.conf  ####
unbind r
bind R source-file ~/.tmux.conf \; display "Reloaded!"


####  KEY BINDINGS  ####
setw -g mode-keys vi

set -g base-index 1          # start indexing windows at 1 instead of 0
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g escape-time 0         # zero-out escape time delay
set -g history-limit 1000000 # increase history size (from 2,000)
set -g mouse on              # enable mouse support
set -g focus-events on       # enable focus events
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
set -g status-interval 3     # update the status bar every 3 seconds
bind-key x kill-pane         # skip "kill-pane 1? (y/n)" prompt

#### Pane resizing ####
bind -r S-Left resize-pane -L 5
bind -r S-Down resize-pane -D 5
bind -r S-Up resize-pane -U 5
bind -r S-Right resize-pane -R 5
bind -r m resize-pane -Z

#### Navigation ####
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

##### Splits ####
unbind '"'
unbind %
bind v split-window -h -c "#{pane_current_path}"
bind S split-window -v -c "#{pane_current_path}"

# New windows in same directory
bind c new-window -c "#{pane_current_path}"

#### status bar ####
set-option -g status-position top
bind u set -g status

##### Display Popups #####
bind f display-popup -w 80% -h 80% -E 'rmpc'

bind -r g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit

##### scripts #####
bind C-l display-popup -w 40% -h 20% -E "~/Scripts/clone"
bind C-k run-shell 'tmux neww ~/Scripts/sessionX'
bind C-c run-shell "~/Scripts/sessionX ~/workspace/.config/"
bind C-p run-shell '~/Scripts/sessionX ~/Projects/'
bind C-g run-shell "~/Scripts/open_github"
bind C-j run-shell "~/Scripts/ide"

##### Display Menu ##### 
bind l display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  "sessionX"      x  "display-popup -E -w 80% -h 80% 'nvim ~/Scripts/sessionX'" \
  "aliases.fish"  f  "display-popup -E -w 80% -h 80% 'nvim ~/.config/fish/aliases.fish'" \
  "tmux.conf"     t  "display-popup -E -w 80% -h 80% 'nvim ~/.config/tmux/tmux.conf'" \
  "bindings.conf" b  "display-popup -E -w 80% -h 80% 'nvim ~/.config/hypr/bindings.conf'" \
  "keymaps.lua"   k  "display-popup -E -w 80% -h 80% 'nvim ~/.config/nvim/lua/config/keymaps.lua'" \
  "Exit"          q  ""

#### Plugins ####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

#### statusline ####
set -g mode-style "fg=black,bg=cyan"
set -g message-style "fg=#fafafa,bg=#18181b"
set -g message-command-style "fg=#fafafa,bg=#18181b"
set -g pane-border-style "fg=#27272a"
set -g pane-active-border-style "fg=cyan"
set -g status "on"
set -g status-interval 1
set -g status-justify "centre"
set -g status-style "fg=#fafafa,bg=#09090b"
set -g status-bg "#09090b"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#fafafa,bg=#09090b,bold]#S#[fg=#52525b]:#[fg=#71717a]#(tmux list-sessions | wc -l)  "
set -g status-right "#[fg=#52525b]%H:%M"
setw -g window-status-activity-style "underscore,fg=cyan,bg=#09090b"
setw -g window-status-separator "  "
setw -g window-status-style "NONE,fg=#52525b,bg=#09090b"
setw -g window-status-format '#[fg=#71717a]#I#[fg=#52525b]:#W'
setw -g window-status-current-format '#[fg=cyan,bold]#I#[fg=cyan,bold]:#W'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
